---
version: '3'

services:
  app:
    build: app
    env_file:
      - variables.env
    depends_on:
      - db

  db:
    image: mariadb
    env_file:
      - variables.env

  web:
    build: web
    env_file:
      - variables.env
    ports:
      - 8000:80

